language: java
jdk:
  - oraclejdk8
  - oraclejdk9
script: ./gradlew build minJosmVersionClasses

deploy:
  provider: releases
  file_glob: true
  api_key: "${GH_TOKEN}"
  file:
    - "build/dist/matsim.jar"
    - "build/tmp/jar/MANIFEST.MF"
  skip_cleanup: true
  on:
    condition: -n $GH_TOKEN
    tags: true
    jdk: oraclejdk8

jobs:
  include:
    - stage: i18n
      language: python
      python: "3.5"
      install: pip install git+https://github.com/transifex/transifex-client.git@a706ba0cb910e66e852010bcd742221363c7e8be#egg=transifex-client
      script: |
        if [ ! -z "$TRANSIFEX_TOKEN" ]; then
          ./gradlew generatePot
          tx --token="$TRANSIFEX_TOKEN" --force-save --no-interactive init
          git checkout HEAD .tx/config
          tx push -s --no-interactive
        fi

stages:
  - test
  - name: i18n
    if: type = push AND branch = master

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9
  - language: python
